version: "3.3"
services:

  node-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - .env
    ports:
      - "5000:5000"

  python-script:
    build:
      context: .
      dockerfile: Dockerfile.python
    env_file:
      - .env
